### ISSUE TITLE
Refactor main

### ISSUE THREAD

**Issue by peterbrendel** [intpsnobs/ocev-ga#12]
Relates to #11 
:dagger: Main is messed up :dagger: 

 @RicardoStoklosa

**Comment by RicardoStoklosa** [comment]
;-;

**Comment by RicardoStoklosa** [comment]
Ok bro,
i gonna checkit out.
@peterbrendel

**Comment by peterbrendel** [comment]
I'm working on it.
Gonna open a new PR

**Comment by RicardoStoklosa** [comment]
Nice!!
if you need help, let me know.

**Comment by RicardoStoklosa** [comment]
@peterbrendel 
vamos tentar deixar a main mais proxima possivel do pseudo codigo de um ga canonico
![image](https://user-images.githubusercontent.com/16613742/76812095-8e838b00-67d2-11ea-8364-c694ba02ef00.png)
Eu acho que ficaria legal assim. :)

**Comment by peterbrendel** [comment]
Ficara para proxima issue
